name: Scheduled Rails Main

on:
  schedule:
    - cron: '0 0 * * 4'

jobs:
  build:
    name: Rails main
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Using Gemfile
        working-directory: ./superglue_rails
        run: |
          mv -f Gemfile.main ./Gemfile
      - name: Bundle install
        working-directory: ./superglue_rails
        run: bundle install
      - name: Run unit test
        working-directory: ./superglue_rails
        run: bundle exec rake test
      - name: Run acceptance test
        working-directory: ./superglue_rails
        run: BUNDLE_GEMFILE='' ruby -Ilib:test test/acceptance/superglue_installation_acceptance.rb
